# This is a basic workflow to help you get started with Actions

name: Automatic Installer creator

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '0 12 15 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  createInstaller:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Download & install Scoop
        run: | 
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
          scoop bucket add extras
      
      - name: Download & install Inno Setup
        run: scoop install inno-setup
        
      - name: Download latest 86box
        run: |
          $repo = "86Box/86Box"
          $filenamePattern = "86Box-Windows-64-b*.zip"
          $source = ((Invoke-RestMethod -Method GET -Uri "https://api.github.com/repos/$repo/releases")[0].assets | Where-Object name -like $filenamePattern ).browser_download_url
          Start-BitsTransfer -Source $source -Destination "86box.zip"
