# This is a basic workflow to help you get started with Actions

name: Automatic Installer creator

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '0 12 15 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  createInstaller:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Download & install Scoop
        run: | 
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
          scoop bucket add extras
      - name: Download & install dependencies
        run: scoop install inno-setup 7zip
      - name: Download latest 86box
        run: |
          $repo = "86Box/86Box"
          $filenamePattern = "86Box-Windows-64-b*.zip"
          $source = ((Invoke-RestMethod -Method GET -Uri "https://api.github.com/repos/$repo/releases")[0].assets | Where-Object name -like $filenamePattern ).browser_download_url
          Start-BitsTransfer -Source $source -Destination "86box.zip"
          expand-archive -path 86box.zip -destination 86boxFiles
      - name: Download latest 86box Manager
        run: |
          $repo = "86Box/86BoxManager"
          $filenamePattern = "86BoxManager_*.zip"
          $source = ((Invoke-RestMethod -Method GET -Uri "https://api.github.com/repos/$repo/releases")[0].assets | Where-Object name -like $filenamePattern ).browser_download_url
          Start-BitsTransfer -Source $source -Destination "86boxManager.zip"
          expand-archive -path 86boxManager.zip -destination 86boxFiles
      - name: Download 86box ROMs
        run: |
          iwr "https://github.com/86Box/roms/archive/refs/heads/master.zip" -OutFile roms.zip
          expand-archive -path roms.zip -destination 86boxFiles
          rename-item -path "86boxFiles\roms-master" -newname "86boxFiles\roms"
      - name: Create 
        run: 7z a 86box.zip .\86boxFiles\*
      - name: 'Upload ZIP'
        uses: actions/upload-artifact@v3
        with:
          name: 86box
          path: 86box.zip
